### PR TITLE
Remove gitignore rule breaking azure sdk vendoring

### PR DESCRIPTION
**Pull request by ibelikov**
Hi!

I was having trouble with code generation without doing explicit `go mod vendor`:
`make gen
Generating Go types
build command-line-arguments: cannot load github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac: open /go/src/kubeform.dev/kubeform/vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac: no such file or directory
Makefile:108: recipe for target 'gen-types' failed`

Turns out .gitignore rule was preventing this:
`git check-ignore -v vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/
.gitignore:11:*.[568vq]	vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/`

Don't think this'll pass CI - looks like it's broken right now due to a move to go 1.14 image, which is out of scope of this PR.

### CODE REVIEW

**Comment by tamalsaha** [comment]
Thanks for your pr @ibelikov ! I have updated the master branch to fix the Go mod issues. Please re-open if this pr is still needed.

**Comment by ibelikov** [comment]
@tamalsaha I believe it's still useful. Even on fresh master (with your recent updates) I can't do `make build` without running `go mod vendor` first:
`Status: Downloaded newer image for appscode/golang-dev:1.14
vendor/github.com/hashicorp/go-azure-helpers/authentication/azure_sp_objectid.go:7:2: cannot find package "." in:
	/src/vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac
Makefile:261: recipe for target 'build' failed`

It works in CI because you explicitly do `go mod tidy` and `go mod vendor`, but that shouldn't be necessary on every run, since all the dependencies are already vendored in the repo.

And it comes down to this small thing with .gitignore

**Comment by ibelikov** [comment]
@tamalsaha I don't have permissions to reopen the PR and don't want to create a new one, but I updated the branch in my fork and rebased it on current master.
Feel free to reopen this one.

Right now this check is basically not working as expected https://github.com/kubeform/kubeform/blob/master/Makefile#L343-L348

It still downloads missing parts of vendored Azure sdk on each run, but git diff is not able to detect changes due to .gitignore rule

**Comment by tamalsaha** [comment]
You are right about the check not working in Makefile. But I can't see what's wrong. Do you have any thoughts?

Regardless, I have opened a pr and removed the offending lines in .gitignore. Those lines are generated when we create repos in GitHub. Thanks for your persistence.

**Comment by tamalsaha** [comment]
>  I don't have permissions to reopen the PR

What do you mean by that? You should be able to open prs from your fork.

**Comment by ibelikov** [comment]
> What do you mean by that? You should be able to open prs from your fork.

Meant I can't reopen this exact one, could create a new one of course.
Glad that the fix is merged👍

The check itself is ok, it's just `git diff` in it wasn't able to detect any changes because they were falling under .gitignore rules:)

**Pull request closed without merging**
